### ISSUE TITLE
Cut down loading time of handbook page

### ISSUE THREAD

**Issue by damithc** [nus-cs2103/website#117]
May be some form of incremental or on-demand loading instead of trying to load everything at once and freezing the page until everything is loaded?

**Comment by jkt001** [comment]
I have a suggestion on this issue:

1. We "split" the sections of the handbook according to the bullet points (i.e. Preliminaries, Lectures, Project, etc.) into a separate HTML file. Each of that HTML file will then load all sub-sections accordingly.

2. In order to split according to (1), we can combine multiple short sections (such as Programming Languages / Textbook) into one section and perhaps split up the Project section to distinguish the CEs and the main product itself.

3. The main handbook.html page will contain links to each section, which will then load the appropriate contents. The main page can also have some nice cover / title to specifically say that it is the handbook (the current one does not have it).

This way, when students view the main handbook page, they will see links to each section. The page itself would only load the respective links to each section. Hence, unnecessary information (such as the project information when students only want to view exam information) is not loaded since the student would only click the link to the "Exam" subsection and that would only load information regarding the exam.

If my suggestion is ok, I will work on it as soon as possible. Any subsequent changes can be made after a preliminary version is done.

**Comment by damithc** [comment]
The reason why we load everything is because it allows users to find things using Ctrl+F. We may not need that anymore when the site-wide search is implemented (currently in progress). At that point, we can change the handbook page to a more load-on-demand model.
The reason why we have split it into so many small parts is because some of those parts are embedded in other pages. When #32 is done, we can combine some of those fragments into bigger pages (e.g. FAQ, Policies). That will reduce the number of calls to the server.
I suggest we hold off this issue for now, until the site-wide search and #32 are done.

**Comment by damithc** [comment]
@jkt001 You can give #32 a try if you are interested :-)
