### ISSUE TITLE
Typo in contents/handbook.html

### ISSUE THREAD

**Issue by vhazali** [nus-cs2103/website#131]
Line 33 to 38 in contents/handbook.html:
```
    <ul>
        <li><a href="#handbook-theProduct">The product</a></li>
        <li><a href="#handbook-projectScope">Project Scope</a></li>
        <li><a href="#handbook-projectConstraints">Project Constraints</a></li>
        <li><a href="#handbook-deliveables">Deliverables</a></li>
        <ul>
```

line 37 should be:
``` 
        <li><a href="#handbook-deliverables">Deliverables</a></li>
```
Missing **r** in the word handbook-deliverables

**Comment by jkt001** [comment]
This typo also exists in the bottom part of handbook.html, in line 125 and 260:
<pre>'handbook-deliveables',</pre>

So this bug is actually causing a section of the handbook to not be displayed properly.

This is the current state of the handbook:
<img width="866" alt="screen shot 2015-12-31 at 10 25 27" src="https://cloud.githubusercontent.com/assets/8586215/12060759/05d4b04e-afa9-11e5-9c95-f95f1462bad9.png">

While this is if the typo has been corrected:
<img width="854" alt="screen shot 2015-12-31 at 10 25 45" src="https://cloud.githubusercontent.com/assets/8586215/12060762/0e610f50-afa9-11e5-99f5-181cff476771.png">

**Comment by damithc** [comment]
I see. It is serious than I thought. Raising priority. @jkt001 go ahead and submit a PR if you can.

**Comment by jkt001** [comment]
Ok, I'll do it later as soon as I have access to my computer. I am currently away.
