### ISSUE TITLE
README.md : explain how to use rawgit.com to stage the proposed changes

### ISSUE THREAD

**Issue by damithc** [nus-cs2103/website#203]
Is rawgit.com an easier way to stage changes? In that case, we can explain that option in the README.md

**Comment by damithc** [comment]
@acjh any input?

**Comment by acjh** [comment]
Rawgit is great because it reflects the current state of a branch, without having to push separately.
This is especially useful for contributors of several PRs, since github.io only shows `gh-pages` branch.

The link is of the form http://rawgit.com/user/repo/branch/. In this case, `repo` will always be `website`.
For example, the equivalent link to my `gh-pages` branch is https://rawgit.com/acjh/website/gh-pages/.

**Comment by damithc** [comment]
Sounds good. @acjh I'll leave you to update the instructions when you have time.
