### ISSUE TITLE
Yellow highlight looks jarring on blue subheadings

### ISSUE THREAD

**Issue by yj-soh** [nus-cs2103/website#23]
![1unnamed](https://cloud.githubusercontent.com/assets/8586080/10195581/e7738ca4-67c0-11e5-8dcf-e01a7800a2a8.png)
An example above.

Something less saturated would work better.
(Or just **bold** it?)

**Comment by acjh** [comment]
Closing since the [yellow background doesn't look that bad. Highlighting is supposed to be eye catching](https://github.com/nus-cs2103/website/pull/184#issuecomment-239142816).
[We should use highlighting sparingly in headers, but when we do, (it should be) bright and eye-catching.](https://github.com/nus-cs2103/website/pull/173#issuecomment-266051943)
