### ISSUE TITLE
Embedded content: allow loading content from any page

### ISSUE THREAD

**Issue by damithc** [nus-cs2103/website#230]
Currently, embedded contents in the Schedule page can only be parts of the handbook page. It's nice if we can load content from any 'div' in any online page.

**Comment by acjh** [comment]
Currently, it should already load any local file.

There are 2 hurdles for a *complete* solution to allow loading content from *any* page:
1. Ajax requests are subject to the same origin policy.
2. While there are workarounds for 1, some sites (including our website) are dynamically loaded.
> Try putting `http://nus-cs2103.github.io/website/` into https://robwu.nl/cors-anywhere.html

The *proper* solution (especially since we should expect to embed static content) would be to duplicate content in a local file and credit appropriately. In practice, there should be no visual difference to users.

**Comment by damithc** [comment]
@acjh Let's limit it to local files then.
I didn't realize it works for other local files. Works even if the file is not in the same directory, as long as it has `html` extension?

**Comment by acjh** [comment]
Yes, it works even if the file is not in the same directory.
Files without `html` extension are simply inserted as text:
- .../publish.sh
- .../README.md
- .../diagrams/PhasesTimeline.pptx
- .../images/2stars.png
- .../scripts/common.js
- .../styles/common.css

**Comment by acjh** [comment]
@damithc Shall we close this?

**Comment by damithc** [comment]
Yes, we should.
