### ISSUE TITLE
Convert 'What to do if there are teamwork issues' doc to html

### ISSUE THREAD

**Issue by damithc** [nus-cs2103/website#47]
Currently it is in a Google Doc.
The content can be found at https://docs.google.com/document/d/1sXGYn1hsdZivB-IU4EL9_KhaLuWGpNM8PAJ-0_rxeYE/pub?embedded=true

**Comment by Foleosy** [comment]
I have converted it to HTML, but I have a couple of questions.

Do I just add it into the contents folder under "week9-whatToDoIfThereAreTeamworkIssues.html" and push?

Or should I edit "week9.html" such that it displays the converted html file like the "Handbook: Appendix E (Using GitHub Project Hosting)"?

In the latter case, should I then add this into the handbook since there isn't a section there for this already?

**Comment by damithc** [comment]
How about we add it as a new appendix to the handbook?

**Comment by Foleosy** [comment]
Ok. I suppose under it should display similar to how "Handbook: Appendix E (Using GitHub Project Hosting)" does in week9, then?

**Comment by damithc** [comment]
Yes, that's right. :+1:
